global:
  scrape_interval: 15s

remote_write:
  - url: https://YOUR_GRAFANA_CLOUD_URL/api/prom/push
    basic_auth:
      username: "YOUR_USER_ID"
      password: "YOUR_API_KEY"

scrape_configs:
  - job_name: "nodejs-app"
    static_configs:
      - targets: ["node-app:3000"]
